import Head from "next/head";
import { css } from "@emotion/css";
import { Button } from "../components/Button/Button.styled";
import { theme } from "../theme/theme";

export default function Home() {
  return (
    <div
      className={css({
        padding: theme.spaces[10],
        backgroundColor: theme.colors.gray[900],
      })}
    >
      <Head>
        <title>Dopefolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1
          className={css({
            color: theme.colors.indigo[500],
            fontSize: theme.fontSizes.heading1,
            marginBottom: theme.spaces[4],
          })}
        >
          DOPEFOLIO
        </h1>
        <p
          className={css({
            fontSize: theme.fontSizes.large,
            lineHeight: theme.spaces[10],
            marginBottom: theme.spaces[8],
            color: theme.colors.white,
          })}
        >
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi possimus
          voluptate animi fuga iusto distinctio tempora eveniet delectus omnis!
          Magnam eveniet dolores quas facilis minus placeat. Laborum natus eius
          quisquam?
        </p>
        <Button>HELLO</Button>
      </div>
    </div>
  );
}
